export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';